### ISSUE TITLE
Keep getting unexpected illegal token from @imports not being converted

### ISSUE THREAD

**Issue by rezen-** [dev113/grunt-import-js#3]
I have a main.js file that starts like this:

// third party scripts
@import "./js/third_party/jquery-1.11.3.js"; 
@import "./js/third_party/jquery-ui-1.11.4.js";
@import "./js/third_party/d-vis.js";
// our software
@import "navbar.js";

and a Gruntfile.js that has the following example usage in the init config:

import_js: {
      files: {
        expand: true,
        cwd: './',
        src: ['./js/main.js'  ],
        dest: './build',
        ext: '.js'
      }
    }

and the following task that I register
 grunt.registerTask('js', ['import_js']);

When running that task "grunt js", I am able to generate the main.js file but it still has the @import's in it.
I've dove into node_modules/task/import_js.js and it looks like the regex filter might not be working properly (assuming I didn't mess anything else up? VERY new to grunt so there's a good chance I did).

Adding the following in the getReplacedFileContent function (near the bottom where it returns) produces this output.
CODE:
var res = str.match( /@import/g );
console.log( " FILES:", res );
OUTPUT:
FILE: [ '@import',  '@import',  '@import', '@import',  '@import',  '@import' ]
CODE:
var res2 = str.match( /(?:\/\/)\s_@import\s_(['"])(._?.js)\1\s_;/gi );
console.log( "\n\n FILE: \n\n", res2 );
OUTPUT:
FILE: null

Anybody have a clue what's going on?

**Comment by dev113** [comment]
@rezen- 
sorry for the bug. The comment signs were previously not really optional. Contrary to what is written in the description.

I've just fixed it. Please use the latest version 0.1.3

**Comment by rezen-** [comment]
No worries :)
what do you mean comment signs? Do you mean the comment that says "//third party scripts"?
or the quotation marks around the file name?

**Comment by dev113** [comment]
I mean the "//" at the beginning of a line before the import statement.

`// @import "...";`

They were previously required. That's why it did not work without them in v0.1.2. In  Version 0.1.3 they are really optional, so that your code should work after an update of the plugin.

**Comment by rezen-** [comment]
ok thanks! marking as closed.
